version: "3.7"
services:
  webapp:
    build: .
    container_name: balance-local
    depends_on:
      - postgres
      - rabbitmq
    restart: always
    environment:
      - "POSTGRES_CONN_STR=postgres://postgres:postgres@postgres/postgres?sslmode=disable"
      - "AMQP_CONN_STR=amqp://user:password@rabbitmq:5672"
    networks:
      - local-net
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - local-net
  postgres:
    image: postgres:12
    container_name: postgres-local-2
    restart: always
    volumes:
      - ./service-data/tmp:/tmp
      - ./service-data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local-net

networks:
  local-net:
